### PR TITLE
Local storage

### PR DESCRIPTION
**Pull request by vimal-oneway**
Screenshot 2023-04-22 142818
Screenshot 2023-04-22 134132

### CODE REVIEW

**Comment by Royal-lobster** [comment]
Awesome ! Could you please provide a brief summary of what this pull request is about ?

**Comment by vimal-oneway** [comment]
Storing chat history in local storage.

**Comment by vimal-oneway** [comment]
Screenshot 2023-04-23 132834

added id, url, timestamp and chat messages to each element of array

**Comment by Royal-lobster** [comment]
> Storing chat history in local storage.

Oh, but i think the "local" in useStorage does the same, it stores the chat on extension's local storage

**Comment by vimal-oneway** [comment]
> > Storing chat history in local storage.
> 
> Oh, but i think the "local" in useStorage does the same, it stores the chat on extension's local storage

"local" in useStorage stores the only one previous chat message but "localStorage" stores all previous chat messages.
"local" stores the collection of messages and "localStorage" stores the collection of chatMessages[]

**Comment by vimal-oneway** [comment]
> > Storing chat history in local storage.
> 
> Oh, but i think the "local" in useStorage does the same, it stores the chat on extension's local storage

we will alter "local" in useStorage  to save collection of chat message with respective url.
ohh yes, I will change "localStorage" into "local".

**Comment by Royal-lobster** [comment]
> > > Storing chat history in local storage.
> > 
> > 
> > Oh, but i think the "local" in useStorage does the same, it stores the chat on extension's local storage
> 
> we will alter "local" in useStorage to save collection of chat message with respective url. ohh yes, I will change "localStorage" into "local".

Ohhh, but it will be better to maintain single chat history across urls, that way if a user is researching on something, they can use it accross various urls while they maintain chat history. but this can be a setting tho. i would change its name to like 'localToSite' in useStorage and add it to chat settings

**Pull request closed without merging**
